steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '-t'
      - 'gcr.io/$PROJECT_ID/weather-mcp-server:$COMMIT_SHA'
      - .
    id: Build Container Image
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - 'gcr.io/$PROJECT_ID/weather-mcp-server:$COMMIT_SHA'
    id: Push Image to Container Registry
  - name: gcr.io/cloud-builders/gcloud
    args:
      - run
      - deploy
      - weather-mcp-server
      - '--image'
      - 'gcr.io/$PROJECT_ID/weather-mcp-server:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - managed
      - '--allow-unauthenticated'
    id: Deploy Container on Google Cloud Run
images:
  - 'gcr.io/$PROJECT_ID/weather-mcp-server:$COMMIT_SHA'