steps:
  # Access the secret
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud secrets versions access latest --secret=firebase-service-account > /workspace/serviceAccountKey.json
        
  # Build the container
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '-t'
      - 'gcr.io/$PROJECT_ID/cloud-run-source-deploy:$COMMIT_SHA'
      - .
      - '--build-arg'
      - 'FIREBASE_SERVICE_ACCOUNT=$$(cat /workspace/serviceAccountKey.json)'
    id: Build Container Image
    secretEnv: ['FIREBASE_SERVICE_ACCOUNT']
    
  # Push the container
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - 'gcr.io/$PROJECT_ID/cloud-run-source-deploy:$COMMIT_SHA'
    id: Push Image to Container Registry
    
  # Deploy to Cloud Run
  - name: gcr.io/cloud-builders/gcloud
    args:
      - run
      - deploy
      - gaterelease
      - '--image'
      - 'gcr.io/$PROJECT_ID/cloud-run-source-deploy:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--set-secrets'
      - 'FIREBASE_SERVICE_ACCOUNT=firebase-service-account:latest'
      - '--platform'
      - managed
      - '--port'
      - '8000'
      - '--memory'
      - '1Gi'
      - '--cpu'
      - '1'
      - '--timeout'
      - '300'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '10'
      - '--concurrency'
      - '80'
    id: Deploy Container on Google Cloud Run

availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/firebase-service-account/versions/latest
      env: FIREBASE_SERVICE_ACCOUNT

images:
  - 'gcr.io/$PROJECT_ID/cloud-run-source-deploy:$COMMIT_SHA'